#!/bin/bash

set -e

if [ -z "$USER" ]; then
  echo "Aborting! No USER environment variable set"
  exit 3;
fi

if [ "$(id -u)" = 0 ]; then
  echo "Aborting! Must not be run as root"
  exit 4
fi

if [ ! -f "$HOME/.ssh/id_rsa.pub" ]; then
  if [ ! -f "$HOME/.ssh/id_ed25519.pub" ]; then
    echo "Ensure you have your GitHub SSH key at ~/.ssh/id_rsa.pub or ~/.ssh/id_ed25519.pub"
    exit 1
  fi
fi

if [ ! -d "nix" ]; then
  echo "Installing nix..."
  sh <(curl -L https://nixos.org/nix/install) --daemon
  # TODO: Need new shell here?
fi

if [ -x "$(command -v home-manager)" ]; then
  echo "Installing home-manager..."
  nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
  nix-channel --update
  nix-shell '<home-manager>' -A install
  home-manager switch
  # TODO: Need new shell here?
fi

if [ ! -d "~/.umbrella" ]; then
  "${SILVERCAT_GIT_CHECKOUTS_DIR:=$HOME/code/gh/bambooengineering}"
  echo "Cloning umbrella into $SILVERCAT_GIT_CHECKOUTS_DIR... (change SILVERCAT_GIT_CHECKOUTS_DIR ENV to put it somewhere else)"
  mkdir -p "$SILVERCAT_GIT_CHECKOUTS_DIR"
  nix shell -p git -c "git clone git@github.com:bambooengineering/umbrella.git $SILVERCAT_GIT_CHECKOUTS_DIR/umbrella"
  ln -s "$SILVERCAT_GIT_CHECKOUTS_DIR/umbrella" ~/.umbrella
fi

# TODO: allow setting umbrella checkout branch if doing work on it etc..
