# Workflow to install bambrew tooling on a Github runner to confirm
# version integrity. Non-zero exit codes should be
# addressed before using bambrew to set up new dev environments.
#
# Runs weekly.

name: CI

on:
  push:
    branches:
      - master
    paths:
      - "**.sh"
  schedule:
    - cron: "* 0 * * 2"
  workflow_dispatch: # for workflow testing

jobs:
  # This workflow contains a single job called "install"
  install:
    runs-on: macos-latest
    steps:
      - run: >
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          sh -c "$(curl -fsSL https://github.com/bambooengineering/bambrew/raw/master/run_bamstrap)"
